### ISSUE TITLE
BusinessDayFrequency error (Python)

### ISSUE THREAD

**Issue by hartziai** [sryza/spark-ts-examples#4]
Getting this error on `BusinessDayFrequency(1, 1, sc)`
`__init__() takes exactly 3 arguments (4 given)`

when I change it to `BusinessDayFrequency(1, sc)` I get this error:

```
--> self._jfreq = sc._jvm.com.cloudera.sparkts.BusinessDayFrequency(bdays)
TypeError: 'JavaPackage' object is not callable
```

**Comment by ahjdzx** [comment]
+1
@sryza 
Did you solve it? @hartziai

**Comment by sryza** [comment]
Hi @hartziai and @ahjdzx, this issue was fixed here: https://github.com/sryza/spark-timeseries/pull/133, but I haven't yet had a chance to include that commit in a release

**Comment by samuelsinayoko** [comment]
I've got a similar error using the latest release `sparkts-0.4.1`
```+ PATH=/miniconda/envs/bmll_python3/bin:/miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ CONDA_PREFIX=/miniconda/envs/bmll_python3
+ PYSPARK_PYTHON=python3
+ /spark/bin/spark-submit --driver-class-path ../target/sparkts-0.4.1-jar-with-dependencies.jar Stocks.py
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/12/05 14:57:18 INFO SparkContext: Running Spark version 2.0.1
16/12/05 14:57:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/12/05 14:57:18 INFO SecurityManager: Changing view acls to: root
16/12/05 14:57:18 INFO SecurityManager: Changing modify acls to: root
16/12/05 14:57:18 INFO SecurityManager: Changing view acls groups to: 
16/12/05 14:57:18 INFO SecurityManager: Changing modify acls groups to: 
16/12/05 14:57:18 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
16/12/05 14:57:19 INFO Utils: Successfully started service 'sparkDriver' on port 39817.
16/12/05 14:57:19 INFO SparkEnv: Registering MapOutputTracker
16/12/05 14:57:19 INFO SparkEnv: Registering BlockManagerMaster
16/12/05 14:57:19 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-8464578a-8752-4752-8bdb-d72eefbf2f12
16/12/05 14:57:19 INFO MemoryStore: MemoryStore started with capacity 366.3 MB
16/12/05 14:57:19 INFO SparkEnv: Registering OutputCommitCoordinator
16/12/05 14:57:19 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
16/12/05 14:57:19 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
16/12/05 14:57:19 INFO Utils: Successfully started service 'SparkUI' on port 4042.
16/12/05 14:57:19 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://172.17.0.2:4042
16/12/05 14:57:20 INFO SparkContext: Added file file:/home/bmll/test-sparkts/python/Stocks.py at file:/home/bmll/test-sparkts/python/Stocks.py with timestamp 1480949840077
16/12/05 14:57:20 INFO Utils: Copying /home/bmll/test-sparkts/python/Stocks.py to /tmp/spark-22dcd6ba-38e4-4d27-8a7a-87493ec06f10/userFiles-0fa39513-dc53-42ea-9a53-0823bae1e36e/Stocks.py
16/12/05 14:57:20 INFO Executor: Starting executor ID driver on host localhost
16/12/05 14:57:20 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42246.
16/12/05 14:57:20 INFO NettyBlockTransferService: Server created on 172.17.0.2:42246
16/12/05 14:57:20 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 172.17.0.2, 42246)
16/12/05 14:57:20 INFO BlockManagerMasterEndpoint: Registering block manager 172.17.0.2:42246 with 366.3 MB RAM, BlockManagerId(driver, 172.17.0.2, 42246)
16/12/05 14:57:20 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 172.17.0.2, 42246)
16/12/05 14:57:21 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 236.5 KB, free 366.1 MB)
16/12/05 14:57:21 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 22.9 KB, free 366.0 MB)
16/12/05 14:57:21 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.17.0.2:42246 (size: 22.9 KB, free: 366.3 MB)
16/12/05 14:57:21 INFO SparkContext: Created broadcast 0 from textFile at NativeMethodAccessorImpl.java:-2
16/12/05 14:57:22 INFO SharedState: Warehouse path is '/home/bmll/test-sparkts/python/spark-warehouse'.
Traceback (most recent call last):
  File "/home/bmll/test-sparkts/python/Stocks.py", line 34, in <module>
    freq = BusinessDayFrequency(1, 1, sc)
TypeError: __init__() takes 3 positional arguments but 4 were given
```
Is there an easy fix?

**Comment by Mahshids** [comment]
Hi @sryza . Did you get a chance to include the fix [#133](https://github.com/sryza/spark-timeseries/pull/133) , in the latest release? I've just started using sparkts. I'm getting the above error in Python.

**Comment by ShakthiYasas** [comment]
Hey @sryza I still get this exact issue mentioned by @hartziai . Hasn't the changes being in effect ?

**Comment by sryza** [comment]
Hey @ShakthiYasas, apologies, but I haven't had the time to do a release since then

**Comment by manj003** [comment]
Any chance to release this fix in future.
